# Generated by Django 5.1.4 on 2025-10-15 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mae_est_sexos',
            name='c_aud_pc',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='mae_est_usuarios_groups',
            name='c_aud_pc',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
