# Generated by Django 5.1.4 on 2025-04-21 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='profile_image',
            field=models.ImageField(default='img_perfil/perfil.png', upload_to='img_perfil/'),
        ),
    ]
