# Generated by Django 5.1.4 on 2025-05-22 21:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0002_hst_usuario_accesos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hst_usuario_accesos',
            name='f_fecha_hora',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
