# Generated by Django 5.1.4 on 2025-05-22 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0003_alter_hst_usuario_accesos_f_fecha_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hst_usuario_accesos',
            name='f_fecha_hora',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
