# Generated by Django 5.1.4 on 2025-04-21 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0003_alter_usuario_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='profile_image',
            field=models.ImageField(default='img_perfil/perfil.png', upload_to='img_perfil/'),
        ),
    ]
