# Generated by Django 5.1.4 on 2025-04-29 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0004_alter_usuario_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='profile_image',
            field=models.ImageField(blank=True, default='img_perfil/perfil.png', null=True, upload_to='img_perfil/'),
        ),
    ]
