# Generated by Django 5.1.4 on 2025-05-22 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0004_alter_hst_usuario_accesos_f_fecha_hora'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='hst_usuario_accesos',
            table='hst_usuario_accesos',
        ),
    ]
