# Generated by Django 5.1.4 on 2025-04-28 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='mae_est_escalas',
            fields=[
                ('n_id_escala', models.AutoField(primary_key=True, serialize=False)),
                ('x_nombre', models.CharField(max_length=100)),
                ('f_fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('f_fecha_baja', models.DateTimeField(null=True)),
                ('x_resolucion', models.CharField(max_length=255)),
                ('x_anio', models.CharField(max_length=4)),
                ('l_activo', models.CharField(default='S', max_length=1)),
            ],
            options={
                'db_table': 'mae_est_escalas',
            },
        ),
        migrations.CreateModel(
            name='mae_est_especialidades',
            fields=[
                ('c_especialidad', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('x_desc_especialidad', models.CharField(max_length=30)),
                ('c_cod_especialidad', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'mae_est_especialidades',
            },
        ),
        migrations.CreateModel(
            name='mae_est_estand_prod',
            fields=[
                ('n_id_estand_prod', models.AutoField(primary_key=True, serialize=False)),
                ('x_resolucion', models.CharField(max_length=200)),
                ('x_prd_res', models.FileField(upload_to='resoluciones/estandar/')),
                ('f_fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('f_fecha_baja', models.DateTimeField(null=True)),
                ('l_activo', models.CharField(default='S', max_length=1)),
            ],
            options={
                'db_table': 'mae_est_estand_prod',
            },
        ),
        migrations.CreateModel(
            name='mae_est_instancia',
            fields=[
                ('c_distrito', models.CharField(max_length=3)),
                ('c_provincia', models.CharField(max_length=4)),
                ('c_instancia', models.CharField(max_length=3)),
                ('n_instancia_id', models.IntegerField(primary_key=True, serialize=False)),
                ('x_nom_instancia', models.CharField(max_length=60)),
                ('n_instancia', models.IntegerField()),
                ('n_modulo', models.IntegerField(blank=True, null=True)),
                ('l_modulo_ejecucion', models.CharField(max_length=1)),
                ('x_corto', models.CharField(max_length=4)),
                ('l_ind_baja', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'mae_est_instancia',
            },
        ),
        migrations.CreateModel(
            name='mae_est_juez_tipos',
            fields=[
                ('n_id_juez_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('x_descripcion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'mae_est_juez_tipos',
            },
        ),
        migrations.CreateModel(
            name='mae_est_modulos',
            fields=[
                ('n_id_modulo', models.AutoField(primary_key=True, serialize=False)),
                ('x_nombre', models.CharField(max_length=100)),
                ('f_fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('f_fecha_baja', models.DateTimeField(null=True)),
                ('l_activo', models.CharField(default='S', max_length=1)),
            ],
            options={
                'db_table': 'mae_est_modulos',
                'permissions': [('list_mae_est_modulos', 'Listar Módulos')],
            },
        ),
        migrations.CreateModel(
            name='mae_est_organo_jurisdiccionales',
            fields=[
                ('c_org_jurisd', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('x_nom_org_jurisd', models.CharField(max_length=30)),
                ('x_nom_org_jurisd_corto', models.CharField(max_length=2)),
                ('l_activo', models.CharField(default='S', max_length=1)),
            ],
            options={
                'db_table': 'mae_est_organo_jurisdiccionales',
            },
        ),
        migrations.CreateModel(
            name='mae_est_sedes',
            fields=[
                ('c_sede', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('x_desc_sede', models.CharField(max_length=60)),
                ('l_activo', models.CharField(default='S', max_length=1)),
            ],
            options={
                'db_table': 'mae_est_sedes',
            },
        ),
        migrations.CreateModel(
            name='mae_est_sub_especialidad_ests',
            fields=[
                ('c_sub_esp', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('x_sub_esp', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'mae_est_sub_especialidad_ests',
            },
        ),
        migrations.CreateModel(
            name='mae_est_tipo_esp',
            fields=[
                ('n_id_tipo_esp', models.AutoField(primary_key=True, serialize=False)),
                ('x_descripcion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'mae_est_tipo_esp',
            },
        ),
        migrations.CreateModel(
            name='mae_est_variables',
            fields=[
                ('var_id', models.IntegerField(primary_key=True, serialize=False)),
                ('var_des', models.CharField(max_length=80)),
                ('var_ord', models.IntegerField()),
                ('var_letra', models.CharField(max_length=2)),
                ('c_estadistica', models.CharField(max_length=5)),
                ('var_ind', models.CharField(max_length=1)),
                ('var_des_det', models.CharField(max_length=255, null=True)),
                ('var_lines_inf', models.CharField(max_length=1, null=True)),
            ],
            options={
                'db_table': 'mae_est_variables',
            },
        ),
        migrations.CreateModel(
            name='mae_est_escala_detalle',
            fields=[
                ('n_id_escala_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('x_mes', models.CharField(max_length=2)),
                ('m_porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('n_id_escala', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='est.mae_est_escalas')),
            ],
            options={
                'db_table': 'mae_est_escala_detalle',
            },
        ),
        migrations.CreateModel(
            name='hst_est_instancia_detalles',
            fields=[
                ('n_id_instancia_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('f_fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('f_fecha_baja', models.DateTimeField(null=True)),
                ('x_resolucion', models.CharField(max_length=200)),
                ('x_pdf_res', models.FileField(upload_to='instancia/')),
                ('n_instancia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='est.mae_est_instancia')),
            ],
            options={
                'db_table': 'hst_est_instancia_detalles',
            },
        ),
        migrations.CreateModel(
            name='conf_est_meta_conf',
            fields=[
                ('n_id_meta_config', models.AutoField(primary_key=True, serialize=False)),
                ('n_anio_est', models.IntegerField()),
                ('n_mes_est', models.IntegerField()),
                ('m_op_egre_otra_dep', models.IntegerField()),
                ('m_op_ing_otra_dep', models.IntegerField()),
                ('m_op_pend_reserva', models.IntegerField()),
                ('f_fecha_mod', models.DateTimeField(null=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('n_instancia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='est.mae_est_instancia')),
            ],
            options={
                'db_table': 'conf_est_meta_conf',
            },
        ),
        migrations.CreateModel(
            name='mae_est_instancia_estandares',
            fields=[
                ('n_id_instancia_estandar', models.AutoField(primary_key=True, serialize=False)),
                ('m_estandar_prod', models.DecimalField(decimal_places=2, max_digits=7)),
                ('f_fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('f_fecha_baja', models.DateTimeField(null=True)),
                ('l_activo', models.CharField(default='S', max_length=1)),
                ('n_id_estand_prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='est.mae_est_estand_prod')),
                ('n_instancia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='est.mae_est_instancia')),
            ],
            options={
                'db_table': 'mae_est_instancia_estandares',
            },
        ),
        migrations.CreateModel(
            name='mae_est_jueces',
            fields=[
                ('n_id_juez', models.AutoField(primary_key=True, serialize=False)),
                ('l_activo', models.CharField(default='S', max_length=1)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('n_id_juez_tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='est.mae_est_juez_tipos')),
            ],
            options={
                'db_table': 'mae_est_jueces',
                'permissions': [('list_mae_est_jueces', 'Listar Jueces')],
            },
        ),
        migrations.CreateModel(
            name='mae_est_meta_detalles',
            fields=[
                ('n_id_meta_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('n_anio_est', models.IntegerField()),
                ('n_mes_est', models.IntegerField()),
                ('m_t_resuelto_mes', models.IntegerField()),
                ('m_t_ingreso_mes', models.IntegerField()),
                ('f_fecha_mod', models.DateTimeField(auto_now=True)),
                ('c_especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='est.mae_est_especialidades')),
                ('n_instancia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='est.mae_est_instancia')),
            ],
            options={
                'db_table': 'mae_est_meta_detalles',
            },
        ),
        migrations.CreateModel(
            name='mae_est_meta_resumenes',
            fields=[
                ('n_id_meta_resumen', models.AutoField(primary_key=True, serialize=False)),
                ('n_anio_est', models.IntegerField()),
                ('n_mes_est', models.IntegerField()),
                ('m_estandar_prod', models.IntegerField()),
                ('n_carg_procesal_ini', models.IntegerField()),
                ('m_t_resuelto', models.IntegerField()),
                ('m_t_ingreso', models.IntegerField()),
                ('m_ing_proyectado', models.IntegerField()),
                ('m_carg_procesal_tram', models.IntegerField()),
                ('m_carg_procesal_min', models.IntegerField()),
                ('m_carg_procesal_max', models.IntegerField()),
                ('m_egre_otra_dep', models.IntegerField()),
                ('m_ing_otra_dep', models.IntegerField()),
                ('m_pend_reserva', models.IntegerField()),
                ('m_meta_preliminar', models.IntegerField()),
                ('x_situacion_carga', models.CharField(max_length=20)),
                ('m_avan_meta', models.DecimalField(decimal_places=2, max_digits=5)),
                ('m_ideal_avan_meta', models.IntegerField()),
                ('m_ideal_avan_meta_ant', models.IntegerField(null=True)),
                ('x_niv_produc', models.CharField(max_length=20)),
                ('m_niv_bueno', models.IntegerField()),
                ('m_niv_muy_bueno', models.IntegerField()),
                ('f_fecha_mod', models.DateTimeField(auto_now=True)),
                ('n_instancia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='est.mae_est_instancia')),
                ('n_id_modulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='est.mae_est_modulos')),
            ],
            options={
                'db_table': 'mae_est_meta_resumenes',
            },
        ),
        migrations.AddField(
            model_name='mae_est_instancia',
            name='c_org_jurisd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='est.mae_est_organo_jurisdiccionales'),
        ),
        migrations.CreateModel(
            name='mae_est_acto_procesales',
            fields=[
                ('c_acto_procesal', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('x_desc_acto_procesal', models.CharField(max_length=150)),
                ('l_activo', models.CharField(default='S', max_length=1, null=True)),
                ('c_especialidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='est.mae_est_especialidades')),
                ('c_org_jurisd', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='est.mae_est_organo_jurisdiccionales')),
            ],
            options={
                'db_table': 'mae_est_acto_procesales',
            },
        ),
        migrations.AddField(
            model_name='mae_est_instancia',
            name='c_sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='est.mae_est_sedes'),
        ),
        migrations.CreateModel(
            name='mov_est_estprod_anuales',
            fields=[
                ('n_id_instancia_factor', models.AutoField(primary_key=True, serialize=False)),
                ('m_estandar_prod', models.IntegerField()),
                ('m_carga_min', models.DecimalField(decimal_places=2, max_digits=5)),
                ('m_carga_max', models.DecimalField(decimal_places=2, max_digits=5)),
                ('m_meta_preliminar', models.DecimalField(decimal_places=2, max_digits=5)),
                ('m_meta_final', models.DecimalField(decimal_places=2, max_digits=5)),
                ('f_fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('f_fecha_baja', models.DateTimeField(null=True)),
                ('l_org_penal', models.CharField(default='S', max_length=1)),
                ('l_unico_especialidad', models.CharField(default='S', max_length=1)),
                ('l_volencia_familiar', models.CharField(default='S', max_length=1)),
                ('c_zona', models.CharField(max_length=1)),
                ('l_activo', models.CharField(default='S', max_length=1)),
                ('n_id_tipo_esp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='est.mae_est_tipo_esp')),
                ('n_instancia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='est.mae_est_instancia')),
            ],
            options={
                'db_table': 'mae_est_instancia_factores',
            },
        ),
        migrations.CreateModel(
            name='mov_est_instancia_escalas',
            fields=[
                ('n_id_instancia_escala', models.AutoField(primary_key=True, serialize=False)),
                ('f_fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('f_fecha_baja', models.DateTimeField(null=True)),
                ('l_activo', models.CharField(default='S', max_length=1)),
                ('l_id_escala', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='est.mae_est_escalas')),
                ('n_instancia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='est.mae_est_instancia')),
            ],
            options={
                'db_table': 'mov_est_instancia_escalas',
            },
        ),
        migrations.CreateModel(
            name='mov_est_instancia_jueces',
            fields=[
                ('n_id_instancia_juez', models.AutoField(primary_key=True, serialize=False)),
                ('x_resolucion', models.CharField(max_length=200)),
                ('x_pdf_res', models.FileField(upload_to='instancia/')),
                ('f_fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('f_fecha_baja', models.DateTimeField(null=True)),
                ('l_activo', models.CharField(default='S', max_length=1)),
                ('n_id_juez', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='est.mae_est_jueces')),
                ('n_instancia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='est.mae_est_instancia')),
            ],
            options={
                'db_table': 'mov_est_instancia_jueces',
            },
        ),
        migrations.CreateModel(
            name='mov_est_instancia_modulos',
            fields=[
                ('n_id_instancia_modulo', models.AutoField(primary_key=True, serialize=False)),
                ('f_fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('f_fecha_baja', models.DateTimeField(null=True)),
                ('l_activo', models.CharField(default='S', max_length=1)),
                ('n_id_modulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='est.mae_est_modulos')),
                ('n_instancia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='est.mae_est_instancia')),
            ],
            options={
                'db_table': 'mov_est_instancia_modulos',
            },
        ),
        migrations.CreateModel(
            name='mov_est_instancia_usuarios',
            fields=[
                ('n_id_instancia_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('f_fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('f_fecha_baja', models.DateTimeField(null=True)),
                ('l_activo', models.CharField(default='S', max_length=1)),
                ('n_instancia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='est.mae_est_instancia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mov_est_instancia_usuarios',
            },
        ),
        migrations.CreateModel(
            name='mov_est_modulo_usuarios',
            fields=[
                ('n_id_modulo_usuario', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('f_fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('f_fecha_baja', models.DateTimeField(null=True)),
                ('l_activo', models.CharField(default='S', max_length=1)),
                ('n_id_modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='est.mae_est_modulos')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mov_est_modulo_usuarios',
            },
        ),
        migrations.CreateModel(
            name='mov_est_var_periodos',
            fields=[
                ('id_var_periodos', models.AutoField(primary_key=True, serialize=False)),
                ('n_anio_est', models.IntegerField()),
                ('n_mes_est', models.IntegerField()),
                ('n_dependencia', models.IntegerField()),
                ('n_funcion', models.IntegerField()),
                ('n_cant_var', models.IntegerField()),
                ('c_especialidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='est.mae_est_especialidades')),
                ('c_sub_especialidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='est.mae_est_sub_especialidad_ests')),
                ('n_instancia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='est.mae_est_instancia')),
                ('var', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='est.mae_est_variables')),
            ],
            options={
                'db_table': 'mov_est_var_periodos',
            },
        ),
    ]
