# Generated by Django 5.1.4 on 2025-10-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('est', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='mae_est_sub_especilidad',
            fields=[
                ('f_aud', models.DateTimeField(auto_now=True, null=True)),
                ('b_aud', models.CharField(default='I', max_length=1, null=True)),
                ('c_aud_uid', models.CharField(blank=True, max_length=30, null=True)),
                ('c_aud_uidred', models.CharField(blank=True, max_length=30, null=True)),
                ('n_aud_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('c_aud_mcaddr', models.CharField(blank=True, max_length=17, null=True)),
                ('n_id_sub_esp', models.AutoField(primary_key=True, serialize=False)),
                ('c_sub_esp', models.CharField(max_length=2)),
                ('x_sub_esp', models.CharField(max_length=100)),
                ('n_orden', models.IntegerField()),
                ('l_activo', models.CharField(default='S', max_length=1)),
            ],
            options={
                'db_table': 'mae_est_sub_especilidad',
            },
        ),
        migrations.AddField(
            model_name='mae_est_civil_meta_pre',
            name='n_meta_preliminar_ci',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
