# Generated by Django 5.1.4 on 2025-04-29 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('est', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mov_est_modulo_usuarios',
            options={'permissions': [('list_mov_est_modulo_usuarios', 'Listar Administrador Módulos')]},
        ),
    ]
