# Generated by Django 5.1.4 on 2025-04-29 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('est', '0002_alter_mov_est_modulo_usuarios_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mov_est_modulo_usuarios',
            name='n_id_modulo_usuario',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
