# Generated by Django 5.1.4 on 2025-10-15 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('est', '0002_mae_est_sub_especilidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conf_est_meta_conf',
            name='c_aud_pc',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='hst_est_instancia_detalles',
            name='c_aud_pc',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='hst_usuario_accion',
            name='c_aud_pc',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='mae_est_acto_procesales',
            name='c_aud_pc',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='mae_est_civil_meta_pre',
            name='c_aud_pc',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='mae_est_escala_detalle',
            name='c_aud_pc',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='mae_est_escalas',
            name='c_aud_pc',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='mae_est_especialidades',
            name='c_aud_pc',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='mae_est_estand_prod',
            name='c_aud_pc',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='mae_est_instancia',
            name='c_aud_pc',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='mae_est_instancia_estandares',
            name='c_aud_pc',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='mae_est_jueces',
            name='c_aud_pc',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='mae_est_juez_tipos',
            name='c_aud_pc',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='mae_est_meta_detalles',
            name='c_aud_pc',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='mae_est_meta_resumenes',
            name='c_aud_pc',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='mae_est_meta_resumenes_modificado',
            name='c_aud_pc',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='mae_est_modulos',
            name='c_aud_pc',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='mae_est_organo_jurisdiccionales',
            name='c_aud_pc',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='mae_est_sedes',
            name='c_aud_pc',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='mae_est_sub_especialidad_ests',
            name='c_aud_pc',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='mae_est_sub_especilidad',
            name='c_aud_pc',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='mae_est_tipo_esp',
            name='c_aud_pc',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='mae_est_variables',
            name='c_aud_pc',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='mov_est_estprod_anuales',
            name='c_aud_pc',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='mov_est_instancia_escalas',
            name='c_aud_pc',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='mov_est_instancia_jueces',
            name='c_aud_pc',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='mov_est_instancia_modulos',
            name='c_aud_pc',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='mov_est_instancia_usuarios',
            name='c_aud_pc',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='mov_est_modulo_usuarios',
            name='c_aud_pc',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='mov_est_var_periodos',
            name='c_aud_pc',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
