# Generated by Django 5.1.4 on 2025-10-15 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('est', '0003_conf_est_meta_conf_c_aud_pc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='aud_mae_est_meta_resumenes_modificado',
            fields=[
                ('f_aud', models.DateTimeField(auto_now=True, null=True)),
                ('b_aud', models.CharField(default='I', max_length=1, null=True)),
                ('c_aud_uid', models.CharField(blank=True, max_length=30, null=True)),
                ('c_aud_uidred', models.CharField(blank=True, max_length=30, null=True)),
                ('c_aud_pc', models.CharField(blank=True, max_length=30, null=True)),
                ('n_aud_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('c_aud_mcaddr', models.CharField(blank=True, max_length=17, null=True)),
                ('n_trns_id', models.AutoField(primary_key=True, serialize=False)),
                ('f_trns', models.DateTimeField(auto_now_add=True)),
                ('b_trns', models.CharField(max_length=1)),
                ('c_trns_uid', models.CharField(blank=True, max_length=30, null=True)),
                ('c_trns_pc', models.CharField(blank=True, max_length=30, null=True)),
                ('n_trns_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('c_trns_mcaddr', models.CharField(blank=True, max_length=17, null=True)),
                ('n_id_meta_resumen', models.IntegerField()),
                ('n_anio_est', models.IntegerField()),
                ('n_mes_est', models.IntegerField()),
                ('m_estandar_prod', models.IntegerField()),
                ('n_carg_procesal_ini', models.IntegerField()),
                ('m_t_resuelto', models.IntegerField()),
                ('m_t_ingreso', models.IntegerField()),
                ('m_t_ingreso_proy', models.IntegerField()),
                ('m_ing_proyectado', models.IntegerField()),
                ('m_carg_procesal_tram', models.IntegerField()),
                ('m_carg_procesal_min', models.IntegerField()),
                ('m_carg_procesal_max', models.IntegerField()),
                ('m_egre_otra_dep', models.IntegerField()),
                ('m_ing_otra_dep', models.IntegerField()),
                ('m_pend_reserva', models.IntegerField()),
                ('m_meta_preliminar', models.IntegerField()),
                ('x_situacion_carga', models.CharField(max_length=20)),
                ('m_avan_meta', models.DecimalField(decimal_places=2, max_digits=5)),
                ('m_ideal_avan_meta', models.IntegerField()),
                ('m_ideal_avan_meta_ant', models.IntegerField(null=True)),
                ('x_niv_produc', models.CharField(max_length=20)),
                ('m_niv_bueno', models.IntegerField()),
                ('m_niv_muy_bueno', models.IntegerField()),
                ('f_fecha_mod', models.DateTimeField(auto_now=True)),
                ('l_estado', models.CharField(default='A', max_length=1, null=True)),
                ('n_id_modulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='est.mae_est_modulos')),
                ('n_instancia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='est.mae_est_instancia')),
            ],
            options={
                'db_table': 'aud_mae_est_meta_resumenes_modificado',
            },
        ),
    ]
