# Generated by Django 5.2 on 2025-05-07 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('est', '0003_alter_mov_est_modulo_usuarios_n_id_modulo_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mae_est_organo_jurisdiccionales',
            options={'permissions': [('list_mae_est_organo_jurisdiccionales', 'Listar Organos Jurisdiccionales')]},
        ),
    ]
