# Generated by Django 5.1.4 on 2025-05-13 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('est', '0004_alter_mae_est_organo_jurisdiccionales_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='mae_est_meta_resumenes',
            name='m_t_ingreso_proy',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
